### ISSUE TITLE
Data Persistence

### ISSUE THREAD

**Issue by tdietert** [adjoint-io/nanocoin#2]
Currently, nanocoin persists nothing to disk, and a node's history is wiped clean when the program is stopped. I would like to add a database module such that when new blocks are accepted by nodes, the ledger and blockchain data is persisted to disk. This way nodes won't have to start from scratch everytime.

Ideas:
- LevelDB (super fast key value store)
- SQLite (minimal DB, basically just another fast key value store)
- Any other minimal k/v store that's lightweight and fast

**Comment by carlosdagos** [comment]
Idea:
> Any other minimal k/v store that's lightweight and fast

Have you thought about: https://github.com/acid-state/acid-state ? :)

**Comment by sdiehl** [comment]
Or Haskey: https://github.com/haskell-haskey/haskey

**Comment by tdietert** [comment]
I'll check both of them out, though I'm inclined to use `haskey` because it was a Haskell summer of code project.

**Comment by ianpurton** [comment]
> SQLite (minimal DB, basically just another fast key value store)

It's a realtional database. The benefit is that you can query the database from the command line, very useful during development. i.e. SELECT * FROM transactions WHERE transaction_id = 'sfsdf' etc.

So SQLite would get my vote.

**Comment by dehun** [comment]
Hi. I have wrote similar project and used leveldb for key value store. 
It is actually same db as used in bitcoin.
See https://github.com/dehun/bce/blob/master/src/Bce/DbFs.hs

**Comment by Lupino** [comment]
haskey
