### ISSUE TITLE
How can I peer with someone currently?

### ISSUE THREAD

**Issue by MoonGem** [adjoint-io/nanocoin#34]
Hello! I'd like to find others to peer with, or is this automatic now? :)

Thanks!! I just pulled and built with stack.

**Comment by mihaigiurgeanu** [comment]
If you want to launch many nodes on the same machine, you should use -p option to pass a rpc port and -n option to pass an p2p port, like this:

    nanocoin -p 3001 -n 8001
    nanocoin -p 3002 -n 8002
    nanocoin -p 3003 -n 8003
    nanocoin -p 3004 -n 8004

You should start with p2p ports 8001 and 8002 since they are in the boot list of nodes.

If you want to peer with other ip addresses, you should change the configuration in the Nanocoin.hs file. For example, this is what I used:

    ifs <- getNetworkInterfaces
    let theHost = case find ((isPrefixOf "eth") . name) ifs of
          Nothing -> "127.0.0.1"
          Just i  -> show $ ipv4 i
    
    -- Initialize NodeState & NodeConfig
    nodeState  <- Node.initNodeState genesisBlock
    -- XXX remove hardcoded values, get from config file
    nodeConfig <- Node.initNodeConfig theHost p2pPort rpcPort (Just keys)
    let nodeEnv = Node.NodeEnv nodeConfig nodeState

    -- XXX remove hardcoded values, get from config file
    node1Id <- Utils.mkNodeId "127.0.1.1" 8001
    node2Id <- Utils.mkNodeId "127.0.1.1" 8002
    -- network nodes for docke trusto-net networkd
    node3Id <- Utils.mkNodeId "172.18.0.2" 8001
    node4Id <- Utils.mkNodeId "172.18.0.3" 8001
    -- add current node to the boot nodes
    thisNodeId <- Utils.mkNodeId theHost p2pPort
    let bootnodes = [node3Id, node4Id, thisNodeId]

For this to work you need to add the import:

    import Network.Info (getNetworkInterfaces, NetworkInterface(..))

and to add the dependency for the network-info package in the nanocoin.cabal file:

    network-info      >= 0.2    && <0.3

**Comment by juanzolo** [comment]
I see :) Very helpful!!!!!!

I guess I was mostly curious if the p2p-peering cloud-haskell was fully implemented yet/automatic. I noticed it connects to 127.0.0.1 for bootstrapping currently.

**Comment by tdietert** [comment]
@juanzolo the p2p code with cloud-haskell is indeed implemented, I just haven't gotten around to updating the docs :grimacing: I will let you know when I do so this weekend, and get you started with getting nodes that reside on different networks to discover each other. I was so eager to push the cloud-haskell code that I forgot to update the docs and add a usable config file.

**Comment by tdietert** [comment]
I have fixed a bug in peer discovery and you should now be able to discover non-boot node peers as long as you have a single bootnode specified in the config file up and running :+1:
