### ISSUE TITLE
Private Key Generation

### ISSUE THREAD

**Issue by quantumproducer** [adjoint-io/nanocoin#39]
Hi, what are specifications of private keys in Nano?

https://nano.org/en/explore/summary doesn't say

https://en.bitcoin.it/wiki/Private_key says: In Bitcoin, a private key is a 256-bit number, which can be represented one of several ways. Here is a private key in hexadecimal - 256 bits in hexadecimal is 32 bytes, or 64 characters in the range 0-9 or A-F. 

I need to generate a private key by flipping coin.

**Comment by quantumproducer** [comment]
Hello, why was this closed? This is a fundamental question should be easy to answer.

**Comment by yate** [comment]
You might be looking for https://github.com/nanocurrency/raiblocks

**Comment by quantumproducer** [comment]
Yes, thank you!
